### ISSUE TITLE
Setup/usage instructions?

### ISSUE THREAD

**Issue by apjanke** [gkaguirrelab/gkaModelEye#22]
Hi! I found this library from someone on IRC, and I'm interested in trying it out.

I'm afraid I can't get it working.

```
>> cd ~/local/repos/gkaModelEye/demo/
>> DEMO_eyeRotationGifs
Unrecognized function or variable 'createSceneGeometry'.
Error in DEMO_eyeRotationGifs (line 3)
sg = createSceneGeometry; 
>> addpath ~/local/repos/gkaModelEye/eye
>> DEMO_eyeRotationGifs
Unable to resolve the name human.cornea.
Error in modelEyeParameters (line 183)
        eye.cornea = human.cornea(eye);
Error in createSceneGeometry (line 214)
sceneGeometry.eye = modelEyeParameters('spectralDomain',p.Results.spectralDomain,varargin{:});
Error in DEMO_eyeRotationGifs (line 3)
sg = createSceneGeometry; 
>> 
```

This is on Matlab R2019b.

Could you add a short document explaining how to load this library in to Matlab, and how to call it?

Cheers,
Andrew

**Comment by gkaguirre** [comment]
It looks like you don’t have the entire repo on your path. Perhaps try:

addpath ~/local/repos/gkaModelEye
The README advises the use of toolbox toolbox to configure matlab repos. You might also try that. 

Best,

Geoff

--

Geoffrey Karl Aguirre, MD, PhD
http://gkaguirre.com
Associate Professor of Neurology
University of Pennsylvania

**Comment by apjanke** [comment]
No love.

```
>> addpath ~/local/repos/gkaModelEye/eye/
>> addpath ~/local/repos/gkaModelEye
>> addpath ~/local/repos/gkaModelEye/demo/
>> DEMO_eyeRotationGifs
Unable to resolve the name human.cornea.
Error in modelEyeParameters (line 183)
        eye.cornea = human.cornea(eye);
Error in createSceneGeometry (line 214)
sceneGeometry.eye = modelEyeParameters('spectralDomain',p.Results.spectralDomain,varargin{:});
Error in DEMO_eyeRotationGifs (line 3)
sg = createSceneGeometry; 
>>
```

I'm trying to figure out ToolboxToolbox, but that might be too complicated for me too.

```
>> addpath ~/local/repos/ToolboxToolbox/api/
>> tbUse('gkaModelEye')
Unrecognized function or variable 'tbChooseStrategy'.
Error in tbDeployToolboxes (line 57)
    strategy = tbChooseStrategy(self, persistentPrefs, prefs);
Error in tbUse (line 33)
results = tbDeployToolboxes(persistentPrefs, prefs, 'registered', registered); 
>> 
```

**Comment by DavidBrainard** [comment]
Try addpath(genpath('~/local/repos/gkaModelEye')).  This will recursively put all subdirs of the repo on your path.  Just using addpath() will not descend further down than is explicitly specified.

**Comment by gkaguirre** [comment]
Thanks!

I’ve been spoiled by toolbox toolbox.

**Comment by apjanke** [comment]
> addpath(genpath('~/local/repos/gkaModelEye'))

Hey, that worked! Thanks!

Maybe that could be added to the README, to help out people who don't have Toolbox Toolbox set up?

**Comment by gkaguirre** [comment]
Good suggestion. I’ll add it to the readme. 

Have fun. 

Geoff

**Comment by apjanke** [comment]
Thanks! The new README stuff is helpful.
